#!/bin/bash

echo Running with $1 threads...

# clear contents of profiling file
echo '' > color-exchange_$1t_times

export OMP_SCHEDULE=guided,20
export OMP_NUM_THREADS=$1
export GEGL_TILE_SIZE=2000x2000

echo -ne "Warming cache: 0 runs done.\r"
# just so runs to warm the cache, we are not interested in the results of this run
for i in `seq 1 3`;
do
	(/usr/bin/time coding/build/bin/gegl color-exchange.xml -o ~/Pictures/tacker.jpg) 2> /dev/null
	echo -ne "Warming cache: $i runs done.\r"
done
echo -e "\n Done."


echo -ne "Profiling run time: 0 runs done.\r"

# do many runs and output results into file
for i in `seq 1 50`;
do
	/usr/bin/time -f "%e" -o color-exchange_$1t_times --append coding/build/bin/gegl color-exchange.xml -o ~/Pictures/tacker.jpg
	echo -ne "Profiling run time: $i runs done.\r"
done

echo -e "\n Done."

