#!/bin/bash

# clear contents of profiling file
echo '' > select_prof_raw

# just so runs to warm the cache, we are not interested in the results of this run
for i in `seq 1 3`;
do
	(time GEGL_TILE_SIZE=2000x2000 coding/build/bin/gegl color-exchange.xml -o ~/Pictures/tacker.jpg) 2> /dev/null
done

# do many runs and output results into file
for i in `seq 1 500`;
do
	(time GEGL_TILE_SIZE=2000x2000 coding/build/bin/gegl color-exchange.xml -o ~/Pictures/tacker.jpg) 2>> scolor-exchange_raw
done

# grep -Po "(?<=(Total time:\s))[0-9]*\.[0-9]*s" test_color
